### ISSUE TITLE
why upgrade from Ubuntu 18.

### ISSUE THREAD

**Issue by thanhtruongphan** [xronos-inc/jetson-nano-ubuntu-22.04#2]
have a nice day @elgeeko1 

can I ask a question? I'm new with Jetson... :smile: 

I want to use Ubuntu on Jetson and need install it. I have a project for study that I maked it on raspi4 with ROS2 humble. 
is it possible if i use ubuntu 22.04 from your share? i see you guide to update from ubuntu 18. to ubuntu 22., why is that, i don't understand?

-thanks-

**Comment by elgeeko1** [comment]
NVIDIA customizes some Linux features specifically for Jetson, including the kernel and some drivers for peripherals such as the GPU. This software is programmed on the Jetson using the NVIDIA SDK Manager. The latest version of Ubuntu that was supported for the Jetson Nano is Ubuntu 18.04.

The guide here starts with the NVIDIA SDK to program Ubuntu 18.04 on the Jetson Nano, and then the operating system is upgraded from 18.04 to 20.04 and then finally 22.04.

An alternate method is to use an operating system image that was created in a similar fashion, but distributed after the upgrade was completed, saving you a step. The latest I see for pre-made images is Ubuntu 20.04. See [Q Engineering - Jetson Nano Ubuntu 20](https://github.com/Qengineering/Jetson-Nano-Ubuntu-20-image).

You may consider running ROS in Docker, which would allow you to use the standard 18.04 image without needing to upgrade. You will need to search for instructions on how to do this.

Good luck!
